#!/usr/bin/env bash

# Command to run act (https://github.com/nektos/act) - edit as required
# to test the workflow you are working on

csd=$(dirname ${BASH_SOURCE})

act workflow_dispatch \
  --workflows ./.github/workflows/prepare-release.yml \
  -e "$csd/evt-prepare-release.json" \
  --secret-file "$csd/act.secrets" \
  --reuse #\
  #--verbose
